//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvioRepair.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remonts
    {
        public int ID_Remont { get; set; }
        public int ID_Equipment { get; set; }
        public int ID_Work { get; set; }
        public int ID_Sotrudnik { get; set; }
        public int ID_Zeh { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Status { get; set; }
        public decimal Cost { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
        public virtual Work Work { get; set; }
        public virtual Zeh Zeh { get; set; }
    }
}
