//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvioRepair.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudniki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrudniki()
        {
            this.Remonts = new HashSet<Remonts>();
        }
    
        public int ID_Sotrudnik { get; set; }
        public int ID_Zeh { get; set; }
        public string FIO { get; set; }
        public string Doljnost { get; set; }
        public int Razryad { get; set; }
        public decimal Oklad { get; set; }
        public string PhoneSotrudnik { get; set; }
        public System.DateTime Data_priema { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remonts> Remonts { get; set; }
        public virtual Zeh Zeh { get; set; }
    }
}
