//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvioRepair.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreRegistor
    {
        public int ID_Log { get; set; }
        public int ID_User { get; set; }
        public string Operation { get; set; }
        public string StatusLog { get; set; }
        public string NamePC { get; set; }
        public System.DateTime DateOperation { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
